import config from '../../../config'
import ApiError from '../../../error/ApiError'
import { IUser } from './user.interface'
import { User } from './user.model'
import { generateUserId } from './users.utils'

const createUser = async (user: IUser): Promise<IUser | null> => {
  const createdUser = await User.create(user)
  //autogenerated incremental id
  const id = await generateUserId()

  user.id = id
  //default password
  if (!user.password) {
    user.password = config.default_user_pass as string
  }

  if (!createdUser) {
    throw new ApiError(400, 'Failed to create User!')
  }
  return createdUser
}

export const UserService = {
  createUser,
}
